apiVersion: apps/v1
kind: Deployment
metadata:
  name: jodel-post-app
  namespace: jodel
  labels:
    app: jodel-post-app
spec:
  selector:
    matchLabels:
      app: jodel-post-app
  template:
    metadata:
      labels:
        app: jodel-post-app
    spec:
      containers:
      - name: jodel-post-app
        image: ozgureroglu/jodel_post_service
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /api/healthChecker
            port: 8000
        readinessProbe:
          httpGet:
            path: /api/healthChecker
            port: 80000
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi

